module com.mycompany.client {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires javafx.media;
    requires transitive org.json;

    opens com.mycompany.client to javafx.fxml;
    opens com.mycompany.client.auth.controller to javafx.fxml;
    opens com.mycompany.client.auth.model to javafx.fxml;
    opens com.mycompany.client.difficulty to javafx.fxml;
    opens com.mycompany.client.gameboard.controller to javafx.fxml;
    opens com.mycompany.client.gameboard.model to javafx.fxml;
    opens com.mycompany.client.gameLobby.controller to javafx.fxml;
    opens com.mycompany.client.gameLobby.controller.uicomponents to javafx.fxml;
    opens com.mycompany.client.gameLobby.enums to javafx.fxml;
    opens com.mycompany.client.gameLobby.networking to javafx.fxml;
    opens com.mycompany.client.gameLobby.networking.exception to javafx.fxml;
    opens com.mycompany.client.gameLobby.networking.model.challenge to javafx.fxml;
    opens com.mycompany.client.gameLobby.networking.model.notification to javafx.fxml;
    opens com.mycompany.client.gameLobby.networking.model.user to javafx.fxml;
    opens com.mycompany.client.GameResultVideoManager to javafx.fxml;
    opens com.mycompany.client.mainmenu to javafx.fxml;
    opens com.mycompany.client.matches.data to javafx.fxml;
    opens com.mycompany.client.matches.ui to javafx.fxml;
    opens com.mycompany.client.match_recording to javafx.fxml;
    opens com.mycompany.client.profile to javafx.fxml;
    opens com.mycompany.client.settings.controller to javafx.fxml;
    opens com.mycompany.client.settings.manager to javafx.fxml;
    opens com.mycompany.client.core.navigation to javafx.fxml;
    opens com.mycompany.client.core.server to javafx.fxml;
    opens com.mycompany.client.core.session to javafx.fxml;

    exports com.mycompany.client;
    exports com.mycompany.client.auth;
    exports com.mycompany.client.auth.controller;
    exports com.mycompany.client.auth.model;
    exports com.mycompany.client.difficulty;
    exports com.mycompany.client.gameboard.controller;
    exports com.mycompany.client.gameboard.model;
    exports com.mycompany.client.gameLobby.controller;
    exports com.mycompany.client.gameLobby.controller.uicomponents;
    exports com.mycompany.client.gameLobby.enums;
    exports com.mycompany.client.gameLobby.networking;
    exports com.mycompany.client.gameLobby.networking.exception;
    exports com.mycompany.client.gameLobby.networking.model.challenge;
    exports com.mycompany.client.gameLobby.networking.model.notification;
    exports com.mycompany.client.gameLobby.networking.model.user;
    exports com.mycompany.client.GameResultVideoManager;
    exports com.mycompany.client.mainmenu;
    exports com.mycompany.client.matches.data;
    exports com.mycompany.client.matches.ui;
    exports com.mycompany.client.match_recording;
    exports com.mycompany.client.profile;
    exports com.mycompany.client.settings.controller;
    exports com.mycompany.client.settings.manager;
    exports com.mycompany.client.core.navigation;
    exports com.mycompany.client.core.server;
    exports com.mycompany.client.core.session;

}
